services:
  service-users-db:
    image: postgres:17-alpine
    container_name: users-db
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - pgdata-service-users:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}?sslmode=disable",
        "up"
      ]
    depends_on:
      service-users-db:
        condition: service_healthy
    restart: "no"
  service-users-go-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aygumov-g/service-users-go-app:latest
    container_name: users-go-app
    environment:
      - APP_PORT=$APP_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "$APP_PORT:$APP_PORT"
    depends_on:
      service-users-db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: always

volumes:
  pgdata-service-users:
